# "kick" "form" "message"
warn-type: "form"

message:
  message: "§c[温馨提示] 请用经典界面 §f设置方法: §6"
  message-delay: 60

kick:
  kick-message: "用了经典界面再回来"

form:
  title: "§c[温馨提示] 请用经典界面"
  content: "§c[温馨提示] 请用经典界面 §f设置方法: §6"
  button1: "ok"
  button2: "no"
  form-delay: 60
